In [ ]:
!pip list

In [3]:
# 데이터 로딩, 데이터 전처리, 통계, 시각화
import numpy as np


In [5]:
# ndarray 생성
arr = [1,2,3]
nd1 = np.array( arr )
display(arr, nd1)

[1, 2, 3]

array([1, 2, 3])

In [7]:
# 리스트와 ndarray 차이점 - 브로드캐스트 연산
# 브로드캐스트 연산 : ndarray + 숫자 -> ndarray모든요소개별과 숫자와 연산
nd1 + 3

array([4, 5, 6])

In [11]:
# numpy 인덱싱, 슬라이싱
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
nd2 = np.array( data2d )
nd2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(data2d[1][0] ) # 4
print(nd2[1][0] ) # 4
print(nd2[1 ,0] ) # 4

4
4
4


In [25]:
# 슬라이싱
print( nd2[ : , 0] ) # 모든행의 0번 칼럼들 추출
print( nd2[ : , 0:2] ) # 모든행의 0,1번 칼럼들 추출
# 팬시 인덱싱( 띄엄띄엄 추출 )
print( nd2[ : , [0,2]] ) # 모든행의 0,2번 칼럼들 추출
# 조건 인덱싱
bidx = nd1 > 2 # [False, False,  True]
nd1[ bidx ] # True에 해당하는 값만 추출 -> [3]
nd1[ [True, False, True] ] # [1, 3]

[1 4 7]
[[1 2]
 [4 5]
 [7 8]]
[[1 3]
 [4 6]
 [7 9]]


array([1, 3])

In [28]:
# 2차원 배열
bidx = nd2 % 2 == 0 #짝수 검사
nd2[ bidx ]

array([2, 4, 6, 8])

In [31]:
# range(시작,끝[,증가치-정수])  시작이상, 끝미만의 연속적인 정수 생성
# np.arange(시작,끝[,증가치-실수]) 시작이상, 끝미만의 연속적인 실수 생성
list(range(0,5))
np.arange(0, 0.5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4])

In [45]:
# np.reshape(arr, size=(row,col))
# arr.reshape(arr, size=(row,col))
nd3 = np.arange(12).reshape(4,3)
nd3.reshape(6,2)
# -1 길이 -> 자동계산.
nd3.reshape(2,3,2) # 면, 행, 열

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
# 브로드캐스트 연산
# 배열 끼리 연산 : 같은 위치끼리 연산
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [51]:
# 기술통계함수(description )
# sum(), mean()-평균, min(), max(), var(), std(), quantile()-백분위수
# comsum()-누적합 comprod()-누적곱
# axis = 0 ->행데이터를 읽어 열별 통계 계산
# axis = 1 ->열데이터를 읽어 행별 통계 계산
# axis = None 전체 통계
nd4 = np.arange(6).reshape(2,3)
print(nd4)
# 칼럼별 평균
print( nd4.mean() ) #전체평균
print( nd4.mean(axis=0) ) #칼럼평균
print( nd4.mean(axis=1) ) #행평균


[[0 1 2]
 [3 4 5]]
2.5
[1.5 2.5 3.5]
[1. 4.]


In [114]:
# 판다스 로딩
import pandas as pd

apt_trading = pd.read_excel(
    "./아파트(매매)_실거래가_20221122103658.xlsx" ,
    skiprows=16,
    thousands=",")
apt_trading

C:\Users\younghwankim\anaconda3-22-10\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")


시군구      번지      본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202112   
1      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
2      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
3      서울특별시 강남구 개포동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
4      서울특별시 강남구 개포동    1282  1282.0   0.0       개포래미안포레스트   102.32  202204   
...              ...     ...     ...   ...             ...      ...     ...   
13406  서울특별시 중랑구 중화동     450   450.0   0.0  한신아파트(103~109)    59.76  202207   
13407  서울특별시 중랑구 중화동     450   450.0   0.0  한신아파트(103~109)    84.03  202207   
13408  서울특별시 중랑구 중화동  274-51   274.0  51.0         한영(101)    84.69  202111   
13409  서울특별시 중랑구 중화동  274-51   274.0  51.0         한영(101)    84.69  202204   
13410  서울특별시 중랑구 중화동    11-7    11.0   7.0     현대휴앤미(102동)    76.43  202204   

       계약일  거래금액(만원)   층    건축년도          도로명  해제사유발생일  거래유형          중개사소재지  
0        4    215000   3  1987.0        언주로 3      NaN  중개거래          서울 강남구  
1       12    220000   4  1987.0        언주로 3      NaN  중개거래          서울 강남구  
2       21    220000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
3       27    216000   2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
4        1    369000  13  2020.0      개포로 264      NaN  중개거래  서울 강남구, 서울 양천구  
...    ...       ...  ..     ...          ...      ...   ...             ...  
13406   20     74000   3  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
13407   27     91500  12  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
13408    4     50000   2  2003.0   동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  
13409    9     49900   7  2003.0   동일로144길 74      NaN  중개거래          서울 중랑구  
13410   23     53000   6  2007.0  봉화산로27가길 19      NaN  중개거래          서울 중랑구  

[13411 rows x 15 columns]

In [56]:
url = "https://search.naver.com/search.naver?where=nexearch&sm=top_sug.pre&fbm=1&acr=1&acq=ghksdbf&qdt=0&ie=utf8&query=%ED%99%98%EC%9C%A8"
curr = pd.read_html( url )
len(curr)

1

In [58]:
curr[0].loc[0, :]

통화명          미국 USD
매매기준율        1356.0
전일대비     전일대비하락5.00
등락률          -0.37%
Name: 0, dtype: object

In [65]:
# 시리즈
import pandas as pd
s1 = pd.Series([70,80,90,60], index=["홍",'김','박','최'])
type(s1)

pandas.core.series.Series

In [72]:
my_curr = curr[0]
my_curr

통화명    매매기준율        전일대비     등락률
0      미국 USD  1356.00  전일대비하락5.00  -0.37%
1  일본 JPY 100   956.65  전일대비하락5.02  -0.52%
2    유럽연합 EUR  1391.05  전일대비하락3.84  -0.28%
3      중국 CNY   189.37  전일대비하락0.47  -0.25%
4      영국 GBP  1607.00  전일대비하락1.36  -0.08%
5      호주 AUD   896.79  전일대비하락3.85  -0.43%
6     캐나다 CAD  1009.38  전일대비하락2.25  -0.22%
7    뉴질랜드 NZD   829.60  전일대비하락1.83  -0.22%

In [76]:
# 한개 행 추출시 행내 데이터를 구분하는 인덱스 칼럼명이다
usd = my_curr.loc[0, :]
print(usd)
print("환율=", usd["매매기준율"])

통화명          미국 USD
매매기준율        1356.0
전일대비     전일대비하락5.00
등락률          -0.37%
Name: 0, dtype: object
환율= 1356.0


In [77]:
# 환율만 추출
환율 = my_curr.loc[:, "매매기준율"]
환율

0    1356.00
1     956.65
2    1391.05
3     189.37
4    1607.00
5     896.79
6    1009.38
7     829.60
Name: 매매기준율, dtype: float64

In [83]:
bidx = my_curr.loc[:, "통화명"] == "일본 JPY 100"
환율[ bidx ]
# 환율[ [True,False,False,False,False,False,False,False,] ]

1    956.65
Name: 매매기준율, dtype: float64

In [87]:
apt_trading

시군구      번지      본번    부번             단지명  전용면적(㎡)    계약년월  \
0      서울특별시 강동구 암사동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202112   
1      서울특별시 강동구 암사동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
2      서울특별시 강동구 암사동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202204   
3      서울특별시 강동구 암사동   658-1   658.0   1.0  개포6차우성아파트1동~8동    79.97  202205   
4      서울특별시 강동구 암사동    1282  1282.0   0.0       개포래미안포레스트   102.32  202204   
...              ...     ...     ...   ...             ...      ...     ...   
13406  서울특별시 강동구 암사동     450   450.0   0.0  한신아파트(103~109)    59.76  202207   
13407  서울특별시 강동구 암사동     450   450.0   0.0  한신아파트(103~109)    84.03  202207   
13408  서울특별시 강동구 암사동  274-51   274.0  51.0         한영(101)    84.69  202111   
13409  서울특별시 강동구 암사동  274-51   274.0  51.0         한영(101)    84.69  202204   
13410  서울특별시 강동구 암사동    11-7    11.0   7.0     현대휴앤미(102동)    76.43  202204   

       계약일        거래금액(만원)   층    건축년도          도로명  해제사유발생일  거래유형  \
0        4         215,000   3  1987.0        언주로 3      NaN  중개거래   
1       12         220,000   4  1987.0        언주로 3      NaN  중개거래   
2       21         220,000   2  1987.0        언주로 3      NaN  중개거래   
3       27         216,000   2  1987.0        언주로 3      NaN  중개거래   
4        1         369,000  13  2020.0      개포로 264      NaN  중개거래   
...    ...             ...  ..     ...          ...      ...   ...   
13406   20          74,000   3  1997.0      동일로 752      NaN  중개거래   
13407   27          91,500  12  1997.0      동일로 752      NaN  중개거래   
13408    4          50,000   2  2003.0   동일로144길 74      NaN  중개거래   
13409    9          49,900   7  2003.0   동일로144길 74      NaN  중개거래   
13410   23          53,000   6  2007.0  봉화산로27가길 19      NaN  중개거래   

               중개사소재지  
0              서울 강남구  
1              서울 강남구  
2              서울 강남구  
3              서울 강남구  
4      서울 강남구, 서울 양천구  
...               ...  
13406          서울 중랑구  
13407          서울 중랑구  
13408  서울 송파구, 서울 중랑구  
13409          서울 중랑구  
13410          서울 중랑구  

[13411 rows x 15 columns]

In [91]:
bidx = apt_trading["시군구"] == "서울특별시 강남구 개포동"
apt_trading[ bidx ]

시군구     번지      본번   부번             단지명  전용면적(㎡)    계약년월  계약일  \
0   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202112    4   
1   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202204   12   
2   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202204   21   
3   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202205   27   
4   서울특별시 강남구 개포동   1282  1282.0  0.0       개포래미안포레스트   102.32  202204    1   
..            ...    ...     ...  ...             ...      ...     ...  ...   
58  서울특별시 강남구 개포동    653   653.0  0.0   현대1차101동~106동   177.19  202112    9   
59  서울특별시 강남구 개포동    653   653.0  0.0   현대1차101동~106동    95.40  202201    5   
60  서울특별시 강남구 개포동    654   654.0  0.0             현대2    84.81  202201   15   
61  서울특별시 강남구 개포동    654   654.0  0.0             현대2    84.81  202203   30   
62  서울특별시 강남구 개포동    654   654.0  0.0             현대2   131.83  202204   21   

          거래금액(만원)   층    건축년도      도로명  해제사유발생일  거래유형            중개사소재지  
0          215,000   3  1987.0    언주로 3      NaN  중개거래            서울 강남구  
1          220,000   4  1987.0    언주로 3      NaN  중개거래            서울 강남구  
2          220,000   2  1987.0    언주로 3      NaN  중개거래            서울 강남구  
3          216,000   2  1987.0    언주로 3      NaN  중개거래            서울 강남구  
4          369,000  13  2020.0  개포로 264      NaN  중개거래    서울 강남구, 서울 양천구  
..             ...  ..     ...      ...      ...   ...               ...  
58         355,000   6  1984.0  개포로 303      NaN  중개거래  경기 안양만안구, 서울 강남구  
59         275,000   2  1984.0  개포로 303      NaN  중개거래            서울 강남구  
60         272,000   8  1986.0  언주로 107      NaN  중개거래            서울 강남구  
61         265,000   7  1986.0  언주로 107      NaN  중개거래            서울 강남구  
62         291,500   3  1986.0  언주로 107      NaN  중개거래             인천 서구  

[63 rows x 15 columns]

In [94]:
apt_trading[ ["시군구","단지명","거래금액(만원)"] ]

시군구             단지명        거래금액(만원)
0      서울특별시 강남구 개포동  개포6차우성아파트1동~8동         215,000
1      서울특별시 강남구 개포동  개포6차우성아파트1동~8동         220,000
2      서울특별시 강남구 개포동  개포6차우성아파트1동~8동         220,000
3      서울특별시 강남구 개포동  개포6차우성아파트1동~8동         216,000
4      서울특별시 강남구 개포동       개포래미안포레스트         369,000
...              ...             ...             ...
13406  서울특별시 중랑구 중화동  한신아파트(103~109)          74,000
13407  서울특별시 중랑구 중화동  한신아파트(103~109)          91,500
13408  서울특별시 중랑구 중화동         한영(101)          50,000
13409  서울특별시 중랑구 중화동         한영(101)          49,900
13410  서울특별시 중랑구 중화동     현대휴앤미(102동)          53,000

[13411 rows x 3 columns]

In [97]:
apt_trading[ 0:1 ]
apt_trading[ apt_trading["시군구"]=="서울특별시 강남구 개포동" ]

시군구     번지      본번   부번             단지명  전용면적(㎡)    계약년월  계약일  \
0   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202112    4   
1   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202204   12   
2   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202204   21   
3   서울특별시 강남구 개포동  658-1   658.0  1.0  개포6차우성아파트1동~8동    79.97  202205   27   
4   서울특별시 강남구 개포동   1282  1282.0  0.0       개포래미안포레스트   102.32  202204    1   
..            ...    ...     ...  ...             ...      ...     ...  ...   
58  서울특별시 강남구 개포동    653   653.0  0.0   현대1차101동~106동   177.19  202112    9   
59  서울특별시 강남구 개포동    653   653.0  0.0   현대1차101동~106동    95.40  202201    5   
60  서울특별시 강남구 개포동    654   654.0  0.0             현대2    84.81  202201   15   
61  서울특별시 강남구 개포동    654   654.0  0.0             현대2    84.81  202203   30   
62  서울특별시 강남구 개포동    654   654.0  0.0             현대2   131.83  202204   21   

          거래금액(만원)   층    건축년도      도로명  해제사유발생일  거래유형            중개사소재지  
0          215,000   3  1987.0    언주로 3      NaN  중개거래            서울 강남구  
1          220,000   4  1987.0    언주로 3      NaN  중개거래            서울 강남구  
2          220,000   2  1987.0    언주로 3      NaN  중개거래            서울 강남구  
3          216,000   2  1987.0    언주로 3      NaN  중개거래            서울 강남구  
4          369,000  13  2020.0  개포로 264      NaN  중개거래    서울 강남구, 서울 양천구  
..             ...  ..     ...      ...      ...   ...               ...  
58         355,000   6  1984.0  개포로 303      NaN  중개거래  경기 안양만안구, 서울 강남구  
59         275,000   2  1984.0  개포로 303      NaN  중개거래            서울 강남구  
60         272,000   8  1986.0  언주로 107      NaN  중개거래            서울 강남구  
61         265,000   7  1986.0  언주로 107      NaN  중개거래            서울 강남구  
62         291,500   3  1986.0  언주로 107      NaN  중개거래             인천 서구  

[63 rows x 15 columns]

In [ ]:
# 데이터 추출 2가지
# loc없이 추출
# apt_trading.loc[행, 열]
# 인덱싱, 팬시인덱싱, 슬라이싱, 조건인덱싱 : 행과 열에 적용 가능
# apt_trading.loc[ : , ["시군구","단지명"] ]   모든행의 "시군구" 칼럼 추출
# 모든행의 "시군구" 칼럼에서 "단지명" 칼럼까지 추출
# apt_trading.loc[ : , "시군구":"단지명" ]   
# 
# apt_trading[ 칼럼명] ->인덱싱, 열추출
# apt_trading[ [칼럼명,칼럼명,..] ] -> 팬시인덱싱,열추출
# apt_trading[ 행번호:행번호 ] -> 슬라이싱, 행추출
# apt_trading[ 조건 ] -> 슬라이싱, 행추출


In [102]:
# 삭제하기
# df.drop( 인덱스 , axis=0/1)  axis=0 행삭제, axis=1 열삭제
# drop()은 삭제된 복사본 반환
# drop( inplace = True)  원본 삭제
apt_trading.drop("번지",axis=1)
apt_trading.drop(columns="번지")
apt_trading.drop(columns=["번지","부번","본번"])

시군구             단지명  전용면적(㎡)    계약년월  계약일        거래금액(만원)  \
0      서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202112    4         215,000   
1      서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202204   12         220,000   
2      서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202204   21         220,000   
3      서울특별시 강남구 개포동  개포6차우성아파트1동~8동    79.97  202205   27         216,000   
4      서울특별시 강남구 개포동       개포래미안포레스트   102.32  202204    1         369,000   
...              ...             ...      ...     ...  ...             ...   
13406  서울특별시 중랑구 중화동  한신아파트(103~109)    59.76  202207   20          74,000   
13407  서울특별시 중랑구 중화동  한신아파트(103~109)    84.03  202207   27          91,500   
13408  서울특별시 중랑구 중화동         한영(101)    84.69  202111    4          50,000   
13409  서울특별시 중랑구 중화동         한영(101)    84.69  202204    9          49,900   
13410  서울특별시 중랑구 중화동     현대휴앤미(102동)    76.43  202204   23          53,000   

        층    건축년도          도로명  해제사유발생일  거래유형          중개사소재지  
0       3  1987.0        언주로 3      NaN  중개거래          서울 강남구  
1       4  1987.0        언주로 3      NaN  중개거래          서울 강남구  
2       2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
3       2  1987.0        언주로 3      NaN  중개거래          서울 강남구  
4      13  2020.0      개포로 264      NaN  중개거래  서울 강남구, 서울 양천구  
...    ..     ...          ...      ...   ...             ...  
13406   3  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
13407  12  1997.0      동일로 752      NaN  중개거래          서울 중랑구  
13408   2  2003.0   동일로144길 74      NaN  중개거래  서울 송파구, 서울 중랑구  
13409   7  2003.0   동일로144길 74      NaN  중개거래          서울 중랑구  
13410   6  2007.0  봉화산로27가길 19      NaN  중개거래          서울 중랑구  

[13411 rows x 12 columns]

In [116]:
# 칼럼명 변경
apt_trading.rename(columns={"전용면적(㎡)":"전용면적"} , inplace=True)

In [120]:
# 전용면적 / 3.03 -> 평 저장
apt_trading["pyung"] = round(apt_trading['전용면적'] / 3.03, 2)
apt_trading["계약년"] = apt_trading["계약년월"] // 100
apt_trading["계약월"] = apt_trading["계약년월"] % 100
# apt_trading.head(3) # 앞부분 3줄
# apt_trading.tail(3) # 뒷부분 3줄

In [121]:
# 데이터프레임의 구조 출력
apt_trading.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13411 entries, 0 to 13410
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   시군구       13411 non-null  object 
 1   번지        13407 non-null  object 
 2   본번        13409 non-null  float64
 3   부번        13409 non-null  float64
 4   단지명       13411 non-null  object 
 5   전용면적      13411 non-null  float64
 6   계약년월      13411 non-null  int64  
 7   계약일       13411 non-null  int64  
 8   거래금액(만원)  13411 non-null  int64  
 9   층         13411 non-null  int64  
 10  건축년도      13409 non-null  float64
 11  도로명       13411 non-null  object 
 12  해제사유발생일   594 non-null    float64
 13  거래유형      13411 non-null  object 
 14  중개사소재지    13411 non-null  object 
 15  pyung     13411 non-null  float64
 16  계약년       13411 non-null  int64  
 17  계약월       13411 non-null  int64  
dtypes: float64(6), int64(6), object(6)
memory usage: 1.8+ MB


In [129]:
"a b c".split()[1]
apt_trading['gu'] = apt_trading["시군구"].str.split().str[1] # str Accessor
apt_trading['dong'] = apt_trading["시군구"].str.split().str[2] # str Accessor
apt_trading.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13411 entries, 0 to 13410
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   시군구       13411 non-null  object 
 1   번지        13407 non-null  object 
 2   본번        13409 non-null  float64
 3   부번        13409 non-null  float64
 4   단지명       13411 non-null  object 
 5   전용면적      13411 non-null  float64
 6   계약년월      13411 non-null  int64  
 7   계약일       13411 non-null  int64  
 8   거래금액(만원)  13411 non-null  int64  
 9   층         13411 non-null  int64  
 10  건축년도      13409 non-null  float64
 11  도로명       13411 non-null  object 
 12  해제사유발생일   594 non-null    float64
 13  거래유형      13411 non-null  object 
 14  중개사소재지    13411 non-null  object 
 15  pyung     13411 non-null  float64
 16  계약년       13411 non-null  int64  
 17  계약월       13411 non-null  int64  
 18  gu        13411 non-null  object 
 19  dong      13411 non-null  object 
dtypes: float64(6), int64(6), obj

In [135]:
apt_trading.sort_values(
    by=["거래금액(만원)","전용면적"] , 
    ascending=[True, False]).tail()

시군구       번지     본번     부번        단지명     전용면적    계약년월  \
11688    서울특별시 용산구 한남동      410  410.0    0.0      파르크한남  268.670  202111   
11689    서울특별시 용산구 한남동      410  410.0    0.0      파르크한남  268.950  202112   
8751   서울특별시 성동구 성수동1가  685-700  685.0  700.0  아크로서울포레스트  264.546  202209   
11690    서울특별시 용산구 한남동      410  410.0    0.0      파르크한남  268.670  202204   
802      서울특별시 강남구 청담동      129  129.0    0.0      PH129  273.960  202204   

       계약일  거래금액(만원)   층    건축년도           도로명  해제사유발생일  거래유형  중개사소재지  pyung  \
11688   26   1170000   4  2020.0   유엔빌리지길 80-1      NaN   직거래       -  88.67   
11689   13   1200000   2  2020.0   유엔빌리지길 80-1      NaN   직거래       -  88.76   
8751    30   1300000  47  2020.0    왕십리로 83-21      NaN  중개거래  서울 성동구  87.31   
11690   30   1350000   5  2020.0  유엔빌리지길 80-36      NaN   직거래       -  88.67   
802     28   1450000  16  2020.0    압구정로79길 88      NaN   직거래       -  90.42   

        계약년  계약월   gu   dong  
11688  2021   11  용산구    한남동  
11689  2021   12  용산구    한남동  
8751   2022    9  성동구  성수동1가  
11690  2022    4  용산구    한남동  
802    2022    4  강남구    청담동

In [138]:
# GroupBy : XX별 그룹만들기
# 칼럼내 값의 중복값 재베한 값 추출
print(apt_trading["gu"].unique())
print(apt_trading["gu"].nunique())
print(apt_trading["gu"].value_counts()) # 값별 빈도수

['강남구' '강동구' '강북구' '강서구' '관악구' '광진구' '구로구' '금천구' '노원구' '도봉구' '동대문구' '동작구'
 '마포구' '서대문구' '서초구' '성동구' '성북구' '송파구' '양천구' '영등포구' '용산구' '은평구' '종로구' '중구'
 '중랑구']
25
노원구     923
구로구     886
강남구     874
서초구     779
영등포구    719
강서구     713
송파구     699
은평구     653
중랑구     606
강동구     591
동작구     586
동대문구    577
성북구     550
마포구     526
양천구     485
관악구     484
도봉구     448
서대문구    420
성동구     412
금천구     301
용산구     288
광진구     264
강북구     218
중구      216
종로구     193
Name: gu, dtype: int64


In [148]:
# 그룹별 통계
# df.groupby("기준칼럼명")[["집계칼럼명"]].통계함수()
apt_gu = apt_trading.groupby("gu")  #구별 거래금액 평균
apt_gu[["거래금액(만원)","pyung"]].mean().sort_values("거래금액(만원)", ascending=False)

거래금액(만원)      pyung
gu                            
용산구   226569.444444  34.489965
강남구   222387.929062  29.586053
서초구   212509.043646  29.355610
성동구   152999.150485  26.313762
송파구   151279.656652  25.581831
광진구   119559.753788  26.459242
마포구   110144.294677  23.115266
양천구    99797.082474  24.804557
동작구    87725.170648  20.158635
서대문구   85038.095238  23.217357
강동구    83940.944162  19.626531
영등포구   83092.952712  18.941725
성북구    81410.703636  23.910036
중구     77284.486111  19.644815
종로구    71780.658031  18.224093
동대문구   69342.452340  19.684835
노원구    67929.741062  20.002026
은평구    67253.895865  21.207856
강서구    65640.332398  20.310898
관악구    63765.185950  19.987603
강북구    60449.587156  22.446376
도봉구    58135.915179  21.553415
금천구    52773.853821  19.416213
구로구    52449.599323  18.284819
중랑구    51445.709571  17.293663

In [150]:
# 연속형 데이터 : 실수값
# 범주형 데이터 : 종류
# 연속형 데이터 범주형으로 변환 -> 통계
# pd.cut(
#     처리대상,
#     bins=[구간값모음],
#     labels=[구간별이름모음],
#     right=False # 오른쪽 구간값의 포함여부(좌우경계중 하나만 포함)
# )
apt_trading["pyung_type"] = pd.cut(
    apt_trading["pyung"],  #처리대상. 연속형
    bins = [0, 10, 20, 30, 40, 50, 200],
    labels = ["10평미만","10평대","20평대","30평대","40평대","50평이상"],
    right=False
)

In [151]:
# 평형별 평균 거래금액
apt_trading.groupby("pyung_type")[["거래금액(만원)"]].mean()

거래금액(만원)
pyung_type               
10평미만        20731.269686
10평대         74151.264878
20평대        117325.023677
30평대        166100.732252
40평대        234510.497373
50평이상       346215.685654

In [152]:
# 구별 평형별 평균 거래금액
apt_trading.groupby(["gu","pyung_type"])[["거래금액(만원)"]].mean()

거래금액(만원)
gu  pyung_type               
강남구 10평미만        33367.037037
    10평대         97655.680000
    20평대        229143.939815
    30평대        289751.178947
    40평대        333307.261682
...                       ...
중랑구 10평대         54479.227053
    20평대         74741.134752
    30평대        103165.384615
    40평대        106375.000000
    50평이상       208000.000000

[150 rows x 1 columns]

In [157]:
#  pivot_table : 표형식 그룹별 통계 계산
# df.pivot_table(
#   index = "주칼럼명", # 선택 - 좌측에 표시
#     columns = "부칼럼명",#선택 - 상단에 표시
#     values="집계칼럼명", # 필수
#     aggfunc="통계함수(기본은 mean)"
# )
round(
    apt_trading.pivot_table(
        values="거래금액(만원)",
        index="pyung_type" ,
        columns="gu",
    ), 2
)

gu                강남구        강동구       강북구        강서구        관악구        광진구  \
pyung_type                                                                    
10평미만        33367.04   15598.29  13306.77   17776.85   15907.46   15136.33   
10평대         97655.68   88297.70  56060.94   61773.42   65916.67   94379.22   
20평대        229143.94  115472.88  72209.62   80521.96   84944.63  127249.03   
30평대        289751.18  140366.67  88525.00  116291.25   98070.91  149605.00   
40평대        333307.26  156370.00  86950.00  129291.67  122000.00  192217.75   
50평이상       436520.56  159100.00       NaN  146600.00        NaN  249877.78   

gu                구로구        금천구        노원구        도봉구  ...        성동구  \
pyung_type                                              ...              
10평미만        12268.57   13349.74   17235.90   15399.46  ...   31752.08   
10평대         48552.94   58156.52   60754.35   50384.47  ...  118744.48   
20평대         80290.45   68701.90   83689.08   67147.25  ...  147404.76   
30평대        106400.00   81879.17  108722.45  102311.11  ...  172130.85   
40평대        117933.33  109266.67  114215.79  110833.33  ...  251821.43   
50평이상       141333.33        NaN        NaN  108555.56  ...  619714.29   

gu                성북구        송파구        양천구       영등포구        용산구        은평구  \
pyung_type                                                                     
10평미만        15497.22   40097.06   14372.22   13357.66   28090.74   28111.46   
10평대         76821.02  103683.57   73864.52   86920.53  123488.33   63888.05   
20평대         90205.46  180696.39   98665.57  111319.31  155694.12   81870.85   
30평대        106850.00  200753.85  149990.00  180005.71  262598.38  104283.78   
40평대        118218.75  249252.04  189877.78  233148.75  241223.38  107064.58   
50평이상       140500.00  250889.47  256590.91  296173.91  480231.54  128142.86   

gu                종로구         중구        중랑구  
pyung_type                                   
10평미만        17793.90   21419.52   23715.07  
10평대         73156.84   64431.65   54479.23  
20평대        130802.57  120815.22   74741.13  
30평대        144583.33  130777.78  103165.38  
40평대        177750.00  173750.00  106375.00  
50평이상       161188.38  220062.50  208000.00  

[6 rows x 25 columns]