**머신러닝 모델 학습**

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=100000).fit(iris['data'], iris['target'])

In [2]:
lr.score(iris['data'], iris['target'])

0.9733333333333334

Scikit-Learn 모델 저장하기

In [3]:
import pickle 
# 현재 폴더에 lr.dat을 생성, wb 쓰기모드, 바이너리 
with open('lr.dat', 'wb') as f: # open(경로, 모드)
    pickle.dump(lr, f) # 변수, 파일포인터 (파일을 가르킴)
    # dump(변수, 파일포인터) -> 내보내기 (저장하기)

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Scikit-Learn 모델 불러오기

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()

import pickle
# 현재 폴더에 lr.dat을 읽음, rb 읽기모드, 바이너리 
with open('lr.dat', 'rb') as f:
    model = pickle.load(f) # load(파일포인터) -> 저장된 변수를 불러옴
    # model이라는 이름으로 LR 변수를 불러옴 
    
model.score(iris['data'], iris['target']) 
# 불러온 모델이 정상적으로 동작함을 확인

0.9733333333333334

In [6]:
type(model)

sklearn.linear_model._logistic.LogisticRegression

In [7]:
# warm_start=True인 경우 fit() 함수를 여러번 사용시 재학습
LogisticRegression(warm_start=True) 
# 모델을 저장하면서 저장된 모델에 새로운 데이터를 계속해서 학습하는 경우 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=True)

**웹 서버 설치 및 구동**

In [8]:
!pip install flask

In [9]:
iris['data'][0], iris['target'][0]

(array([5.1, 3.5, 1.4, 0.2]), 0)

In [10]:
import numpy as np
import pickle
from flask import Flask, request

app = Flask(__name__) # 웹 서버 설정

with open('lr.dat', 'rb') as f: # 모델을 불러옴 (LR -> iris 분류)
    ml = pickle.load(f) # ml 이라는 이름으로 모델을 불러옴

@app.route('/') # IP -> url (http://127.0.0.1:5000 접속시 보여줄 화면)
def index(): # P-CAMP라는 문자를 보여줌
    return 'P-CAMP'

import time
@app.route('/sklearn', methods=['GET']) # http://127.0.0.1:5000/sklearn
def sklearn(): # x1~x4까지 대입을 받아 결과를 예측
    global ml
    x1 = request.args.get('x1') # x1 변수 받기
    x2 = request.args.get('x2') # x2 변수 받기
    x3 = request.args.get('x3') # x3 변수 받기
    x4 = request.args.get('x4') # x4 변수 받기

    # 2차원 데이터로 변환 -> [[
    data = np.array([[float(x1), float(x2), float(x3), float(x4)]])
    
    # 저장된 모델을 이용하여 입력받은 데이터를 예측
    result = ml.predict(data), ml.predict_proba(data)
    
    now = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
    return f'{now} 예측 결과 >{str(result)}' # 예측된 결과를  출력
app.run() # 서버를 실행

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [24/Jan/2021 16:05:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2021 16:05:06] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [24/Jan/2021 16:05:10] "GET /sklearn?x1=5.1&x2=3.5&x3=1.4&x4=0.2 HTTP/1.1" 200 -


# /sklearn?x1=5.1&x2=3.5&x3=1.4&x4=0.2

# http://127.0.0.1:5000/sklearn?x1=5.1&x2=3.5&x3=1.4&x4=0.2

In [11]:
iris['data'][0], iris['target'][0]

(array([5.1, 3.5, 1.4, 0.2]), 0)

In [12]:
iris['data'][-1], iris['target'][-1]

(array([5.9, 3. , 5.1, 1.8]), 2)

In [13]:
iris['data'][60], iris['target'][60]

(array([5. , 2. , 3.5, 1. ]), 1)